/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-09-24 12:35:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import functionality.ProjectManager;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("functionality.ProjectManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"Error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\"    content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<meta name=\"author\"      content=\"David & Yasen\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>The Traveler Bulgaria</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/images/gt_favicon.png\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" media=\"screen\" href=\"http://fonts.googleapis.com/css?family=Open+Sans:300,400,700\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom styles for our template -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/bootstrap-theme.css\" media=\"screen\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/main.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"assets/js/html5shiv.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     ");
 ProjectManager.getInstance(); 
      out.write("\r\n");
      out.write("<body class=\"home\">\r\n");
      out.write("\t");

   		response.addHeader("Cache-Control", "no-cache,no-store,private,must-revalidate,max-stale=0,post-check=0,pre-check=0"); 
   		response.addHeader("Pragma", "no-cache"); 
   		response.addDateHeader ("Expires", 0);
  	
      out.write("\r\n");
      out.write("\t<!-- Fixed navbar -->\r\n");
      out.write("\t<div class=\"navbar navbar-inverse navbar-fixed-top headroom\" >\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<!-- Button for smallest screens -->\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\"><span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> </button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\"><img src=\"assets/images/logo4.png\" alt=\"The Traveler Bulgaria\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav pull-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"AllDestinations.jsp\">Destinations</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
if(request.getSession().getAttribute("user") == null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"btn\" href=\"SignIn.jsp\">SIGN IN / SIGN UP</a></li>\r\n");
      out.write("\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"btn\" href=\"LogoutServlet\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"btn\" href=\"profile.jsp\">PROFILE</a></li>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div><!--/.nav-collapse -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> \r\n");
      out.write("\t<!-- /.navbar -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<header id=\"head\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<h1 class=\"lead\">The Traveler Bulgaria</h1>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<p><a class=\"btn btn-default btn-lg\" href=\"SectionUnderConstructionPage.html\">View Top Destinations</a> \r\n");
      out.write("\t\t\t\t<a class=\"btn btn-action btn-lg\" href=\"AllDestinations.jsp\" >View All Destinations</a></p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- /Header -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Intro -->\r\n");
      out.write("\t<div class=\"container text-center\">\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\t\t<h2 class=\"thin\">The best place to tell people where you've been on your last travels and how awesome your experience was!</h2>\r\n");
      out.write("\t\t<p class=\"text-muted\">\r\n");
      out.write("\t\t\tThe difference between involvement and commitment is like an eggs-and-ham breakfast:<br> \r\n");
      out.write("\t\t\tthe chicken was involved; the pig was committed. Be truly committed to what you do!\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /Intro-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- Highlights - jumbotron -->\r\n");
      out.write("\t<div class=\"jumbotron top-space\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3 class=\"text-center thin\">Reasons to use our site</h3>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-sm-6 highlight\">\r\n");
      out.write("\t\t\t\t\t<div class=\"h-caption\"><h4><i class=\"fa fa-cogs fa-5\"></i>User-powered content</h4></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"h-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>All the content in the site is inspired, generated and intended for our users! Our goal is to help you make the perfect Traveler social network and connect with other travelers like you. </p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-sm-6 highlight\">\r\n");
      out.write("\t\t\t\t\t<div class=\"h-caption\"><h4><i class=\"fa fa-flash fa-5\"></i>Burning calories while having fun</h4></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"h-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>Get in your best shape by traveling all over Bulgaria, finding new places, and sharing your experience with your friends! Being fit has never been easier and more enjoyable!</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-sm-6 highlight\">\r\n");
      out.write("\t\t\t\t\t<div class=\"h-caption\"><h4><i class=\"fa fa-heart fa-5\"></i>Beautiful destinations</h4></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"h-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>Reach out and explore an amazing new world you have never seen before! Explore the most breathtaking destinations and live to tell the story!</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-sm-6 highlight\">\r\n");
      out.write("\t\t\t\t\t<div class=\"h-caption\"><h4><i class=\"fa fa-smile-o fa-5\"></i>Finding new places and friends</h4></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"h-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>Bond with people with the same travel interests as yours and keep all your memories of going on new adventures!</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div> <!-- /row  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /Highlights -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- container -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<h2 class=\"text-center top-space\">Frequently Asked Questions</h2>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<h3>What does it cost to sign up?</h3>\r\n");
      out.write("\t\t\t\t<p>- The registration and all the features in the site are FREE! But registering will cost you about 1 minute and a lifetime of adventures!</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<h3>What can I do when I register?</h3>\r\n");
      out.write("\t\t\t\t<p>- You can add new destinations, view already created ones and add them to you list of destinations. You can also add friends, message them, comment on your friends' posts and like them. Just don't forget to have fun!</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div> <!-- /row -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<h3>Can I invite a friend to join from another social network?</h3>\r\n");
      out.write("\t\t\t\t<p>- The feature for logging in from other social medias or inviting a friend there is currently in development. But while you wait, you can like our Facebook page and tell your friends about us! Let's  add more people to our community!</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<h3>Can you tell me more about the Site?</h3>\r\n");
      out.write("\t\t\t\t<p>- You can click on the About icon on the bottom of the page to learn more about the project and all the information you need! Or you can write to us by clicking on the Contact icon! We'll be more than happy to answer you questions!</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div> <!-- /row -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"jumbotron top-space\">\r\n");
      out.write("\t\t\t<h4>The Traveler Bulgaria supports the Keep Inspiring Initiative. To learn more about it click on the button!</h4>\r\n");
      out.write("     \t\t<p class=\"text-right\"><a class=\"btn btn-primary btn-large\" href=\"SectionUnderConstructionPage.html\">Learn more »</a></p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\t<!-- /container -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Social links. @TODO: replace by link/instructions in template -->\r\n");
      out.write("\t<section id=\"social\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"wrapper clearfix\">\r\n");
      out.write("\t\t\t\t<!-- AddThis Button BEGIN -->\r\n");
      out.write("\t\t\t\t<div class=\"addthis_toolbox addthis_default_style\">\r\n");
      out.write("\t\t\t\t<a class=\"addthis_button_facebook_like\" fb:like:layout=\"button_count\"></a>\r\n");
      out.write("\t\t\t\t<a class=\"addthis_button_tweet\"></a>\r\n");
      out.write("\t\t\t\t<a class=\"addthis_button_linkedin_counter\"></a>\r\n");
      out.write("\t\t\t\t<a class=\"addthis_button_google_plusone\" g:plusone:size=\"medium\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- AddThis Button END -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- /social links -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer id=\"footer\" class=\"top-space\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"footer1\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 widget\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"widget-title\">Contact</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<p><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"mailto:#\">thetravellerbulgaria@gmail.com</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\tInfinity Tower, Sofia City, Bulgaria\r\n");
      out.write("\t\t\t\t\t\t\t</p>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 widget\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"widget-title\">Follow us</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"follow-me-icons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"\"><i class=\"fa fa-twitter fa-2\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"\"><i class=\"fa fa-dribbble fa-2\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"\"><i class=\"fa fa-github fa-2\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"https://www.facebook.com/TheTravellerBulgaria/\"><i class=\"fa fa-facebook fa-2\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 widget\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"widget-title\">Our motto</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\"The whole object of travel is not to set foot on foreign land; it is to set foot on one's own country as on a foreign land.\" - G.K. Chesterton</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>So keep moving! But don't forget to take time to stop and smell the roses!</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div> <!-- /row of widgets -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"footer2\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 widget\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"simplenav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Home</a> | \r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"SectionUnderConstructionPage.html\">About</a> |\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"SectionUnderConstructionPage.html\">Sidebar</a> |\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"SectionUnderConstructionPage.html\">Contact</a> |\r\n");
      out.write("\t\t\t\t\t\t\t\t<b><a href=\"signup.html\">Sign up</a></b>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 widget\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\tCopyright &copy; 2016, The Traveler Bulgaria. Designed by David & Yasen</a> \r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div> <!-- /row of widgets -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</footer>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- JavaScript libs are placed at the end of the document so the pages load faster -->\r\n");
      out.write("\t<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/headroom.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/jQuery.headroom.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/template.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
