/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-09-24 13:41:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SignIn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"Error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\"    content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<meta name=\"author\"      content=\"David & Yasen\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>Sign in to The Traveler Bulgaria</title>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"assets/images/gt_favicon.png\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" media=\"screen\" href=\"http://fonts.googleapis.com/css?family=Open+Sans:300,400,700\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom styles for our template -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/bootstrap-theme.css\" media=\"screen\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/main.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"assets/js/html5shiv.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
if(request.getSession().getAttribute("user")!=null){ 
      out.write("\r\n");
      out.write("\t\t");
response.sendRedirect("profile.jsp"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
} 
      out.write("\r\n");
      out.write("\t<!-- Fixed navbar -->\r\n");
      out.write("\t<div class=\"navbar navbar-inverse navbar-fixed-top headroom\" >\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<!-- Button for smallest screens -->\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\"><span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> </button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\"><img src=\"assets/images/logo4.png\" alt=\"Progressus HTML5 template\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav pull-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"AllDestinations.jsp\">Destinations</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a class=\"btn\" href=\"signin.html\">SIGN IN / SIGN UP</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div><!--/.nav-collapse -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> \r\n");
      out.write("\t<!-- /.navbar -->\r\n");
      out.write("\r\n");
      out.write("\t<header id=\"head\" class=\"secondary\"></header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- container -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t<li class=\"active\">User access</li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Article main content -->\r\n");
      out.write("\t\t\t<article class=\"col-xs-12 maincontent\">\r\n");
      out.write("\t\t\t\t<header class=\"page-header\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"page-title\">Sign in</h1>\r\n");
      out.write("\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"thin text-center\">Sign in to your account</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-center text-muted\"><a href=\"SignUp.jsp\">Register</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"javascript:login()\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t<div class=\"top-margin\">\r\n");
      out.write("   \t\t\t  \t\t\t\t\t   <label>Email <span class=\"text-danger\">*</span></label>\r\n");
      out.write("  \t\t\t  \t\t\t\t\t    <input type=\"text\" id=\"userEmail\" name=\"userEmail\" class=\"form-control\" required>\r\n");
      out.write(" \t\t\t \t\t\t\t\t </div>\r\n");
      out.write("  \t\t\t\t\t\t\t\t <div class=\"top-margin\">\r\n");
      out.write("       \t\t\t\t\t\t\t\t <label>Password <span class=\"text-danger\">*</span></label>\r\n");
      out.write("       \t\t\t\t\t\t\t\t <input type=\"password\" id=\"userPassword\" name=\"userPassword\" class=\"form-control\" required>\r\n");
      out.write("   \t\t\t\t\t\t\t\t </div>\r\n");
      out.write("   \t\t\t \t\t\t\t\t<div class =\"top-margin\" id=\"message\">\r\n");
      out.write("   \t\t\t \r\n");
      out.write("   \t\t\t\t\t\t\t\t </div>\r\n");
      out.write("\r\n");
      out.write("  \t\t\t\t\t\t\t\t  <hr>\r\n");
      out.write("\r\n");
      out.write("   \t\t\t \t\t\t\t\t<div class=\"row\">\r\n");
      out.write("   \t\t\t  \t\t\t\t\t   <div class=\"col-lg-8\">\r\n");
      out.write("      \t\t\t\t\t\t\t\t      <b><a href=\"\">Forgot password?</a></b>\r\n");
      out.write("       \t\t\t\t\t\t\t\t </div>\r\n");
      out.write("       \t\t\t \t\t\t\t\t<div class=\"col-lg-4 text-right\">\r\n");
      out.write("       \t \t\t\t\t\t\t\t\t    <button class=\"btn btn-action\" id=\"login\" type=\"submit\">Sign in</button>\r\n");
      out.write("       \t\t\t\t\t\t\t\t </div>\r\n");
      out.write("   \t\t\t\t\t\t\t\t </div>\r\n");
      out.write("   \t\t\t\t\t\t\t\t </form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\t\t\t<!-- /Article -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t<!-- /container -->\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<footer id=\"footer\" class=\"top-space\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer1\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-md-3 widget\">\r\n");
      out.write("                        <h3 class=\"widget-title\">Contact</h3>\r\n");
      out.write("                        <div class=\"widget-body\">\r\n");
      out.write("                            <p><br>\r\n");
      out.write("                                <a href=\"mailto:#\">thetravellerbulgaria@gmail.com</a><br>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                Infinity Tower, Sofia City, Bulgaria\r\n");
      out.write("                            </p>    \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-3 widget\">\r\n");
      out.write("                        <h3 class=\"widget-title\">Follow us</h3>\r\n");
      out.write("                        <div class=\"widget-body\">\r\n");
      out.write("                            <p class=\"follow-me-icons\">\r\n");
      out.write("                                <a href=\"\"><i class=\"fa fa-twitter fa-2\"></i></a>\r\n");
      out.write("                                <a href=\"\"><i class=\"fa fa-dribbble fa-2\"></i></a>\r\n");
      out.write("                                <a href=\"\"><i class=\"fa fa-github fa-2\"></i></a>\r\n");
      out.write("                                <a href=\"https://www.facebook.com/TheTravellerBulgaria/\"><i class=\"fa fa-facebook fa-2\"></i></a>\r\n");
      out.write("                            </p>    \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-6 widget\">\r\n");
      out.write("                        <h3 class=\"widget-title\">Our motto</h3>\r\n");
      out.write("                        <div class=\"widget-body\">\r\n");
      out.write("                            <p>\"The whole object of travel is not to set foot on foreign land; it is to set foot on one's own country as on a foreign land.\" - G.K. Chesterton</p>\r\n");
      out.write("                            <p>So keep moving! But don't forget to take time to stop and smell the roses!</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div> <!-- /row of widgets -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer2\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-md-6 widget\">\r\n");
      out.write("                        <div class=\"widget-body\">\r\n");
      out.write("                            <p class=\"simplenav\">\r\n");
      out.write("                                <a href=\"#\">Home</a> | \r\n");
      out.write("                                <a href=\"SectionUnderConstructionPage.html\">About</a> |\r\n");
      out.write("                                <a href=\"SectionUnderConstructionPage.html\">Sidebar</a> |\r\n");
      out.write("                                <a href=\"SectionUnderConstructionPage.html\">Contact</a> |\r\n");
      out.write("                                <b><a href=\"signup.html\">Sign up</a></b>\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-6 widget\">\r\n");
      out.write("                        <div class=\"widget-body\">\r\n");
      out.write("                            <p class=\"text-right\">\r\n");
      out.write("                                Copyright &copy; 2016, The Traveler Bulgaria. Designed by David & Yasen</a> \r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div> <!-- /row of widgets -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- JavaScript libs are placed at the end of the document so the pages load faster -->\r\n");
      out.write("\t<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/headroom.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/jQuery.headroom.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/template.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\tfunction login(){\r\n");
      out.write("\t\t\tvar userEmail = $(\"#userEmail\").val();\r\n");
      out.write("\t\t\tvar userPassword = $(\"#userPassword\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"login\",\r\n");
      out.write("\t\t\t\tmethod : \"POST\",\r\n");
      out.write("\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\tuserEmail : userEmail,\r\n");
      out.write("\t\t\t\t\tuserPassword : userPassword\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(results){\r\n");
      out.write("\t\t\t\t\tif(results!=null && results != \"\"){\r\n");
      out.write("\t\t\t\t\t\tshowMessage(results);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"Some error occured, try again.\")\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction showMessage(results){\r\n");
      out.write("                if(results == 'SUCCESS'){\r\n");
      out.write("                    $('#message').html(\"<font color='green'>You are successfully logged in. </font>\")\r\n");
      out.write("                    setTimeout(function(){\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href = \"index.jsp\";\r\n");
      out.write("\t\t\t\t\t\t}, 500)\r\n");
      out.write("                }else if(results == 'FAILURE'){\r\n");
      out.write("                    $('#message').html(\"<font color='red'>Username or password incorrect </font>\")\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
